apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-search
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hungryman
spec:
  params:
  - name: annotations
    value: 
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: hungrymandb 
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-1
  source:
    git:
      url: https://github.com/gm2552/hungryman-search.git
      ref:
        branch: main