---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-search
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hungryman
spec:
  params:
  - name: annotations
    value: 
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: hungrymandb 
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-knative
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: main
    subPath: hungryman-search
---

apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-search-proc
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hungryman
    networking.knative.dev/visibility: cluster-local
spec:
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: kneventing
    subPath: hungryman-search-proc
    
---

apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-notify
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hungryman
    networking.knative.dev/visibility: cluster-local
spec:
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: kneventing
    subPath: hungryman-notify
---

apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-availability
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hungryman
spec:
  params:
  - name: annotations
    value: 
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: hungrymandb
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: kneventing
    subPath: hungryman-availability