apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hungryman-messaging
  description: Hungryman application asynch messaging
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  type: message-broker
  owner: hungryman-team
  system: hungryman