server:
  port: 8081
  forward-headers-strategy: framework
  use-forward-headers: true

hungryman:
  searchEvent:
    period: 120000
    
spring: 
  sql.init.platform: mysql
  sql.init.mode: ALWAYS 
  
  r2dbc: 
    #Default properties to work with MariaDB driver
    properties.sslMode: TRUST  
    properties.tlsVersion: TLSv1.2
  
  cloud: 
    stream:
      poller:
        fixed-delay: ${hungryman.searchEvent.period} 
      function:
        definition: submittedSearches
      bindings: 
        submittedSearches-out-0: 
          destination: hungryman-search-criteria

springdoc:
  packages-to-scan: com.java.example.tanzu.hungryman.resources
  show-spring-cloud-functions: false
          
---

spring:
  config.activate.on-profile: local

  
  sql.init.platform: h2
  sql.init.mode: ALWAYS 
  
  r2dbc: 
    properties.sslMode:   
    properties.tlsVersion: 