hungryman:
  searchEvent:
    period: 120000
    
spring: 
  sql.init.platform: mysql
  sql.init.mode: ALWAYS 
  
  r2dbc: 
    #Default properties to work with MariaDB driver
    properties.sslMode: TRUST  
    properties.tlsVersion: TLSv1.2
  
  cloud: 
    stream:
      poller:
        fixed-delay: ${hungryman.searchEvent.period} 
      function:
        definition: submittedSearches
      bindings: 
        submittedSearches-out-0: 
          destination: hungryman-search-criteria
