apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hungryman-search
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=hungryman"
spec:
  type: service
  lifecycle: experimental
  owner: meyerg@vmware.com
  providesApis:
  - hungryman-search
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hungryman-search
  description: The Search API
  tags:
    - api
    - tanzu
spec:
  type: openapi
  lifecycle: experimental
  owner: default-team
  definition:
    $text: http://hungryman.perfect300rock.com/api/search/v3/api-docs/
