apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: hungryman-sequence
  namespace: workloads
spec:
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: hungryman-search-proc
      uri: /processSearch
    - ref:
      uri: http://hungryman-available-parallel-kn-parallel-kn-channel.workloads.svc.cluster.local
---
apiVersion: flows.knative.dev/v1
kind: Parallel
metadata:
  name: hungryman-available-parallel
  namespace: workloads
spec:
  branches:
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: hungryman-availability
        uri: /processAvailability
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: hungryman-notify
        uri: /notifyAvailability

---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  labels:
    eventing.knative.dev/SourceName: rmq-source
  name: hungryman-search-criteria-exchnage
  namespace: service-instances
spec:
  durable: true
  name: hungryman-search-criteria
  rabbitmqClusterReference:
    name: rmq-knative
    namespace: service-instances
  type: topic
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  labels:
    eventing.knative.dev/SourceName: rmq-source
  name: hungryman-search-criteria-queue
  namespace: service-instances
spec:
  durable: true
  autoDelete: false
  name: hungryman-search-criteria
  rabbitmqClusterReference:
    name: rmq-knative
    namespace: service-instances
  type: quorum
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  labels:
    eventing.knative.dev/SourceName: rmq-source
  name: hungryman-search-criteria-binding
  namespace: service-instances
spec:
  source: hungryman-search-criteria
  destination: hungryman-search-criteria
  destinationType: queue
  routingKey: "#"
  rabbitmqClusterReference:
    name: rmq-knative
    namespace: service-instances
  vhost: /
---
apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: hungryman-search-criteria-rabbit-source
  namespace: service-instances
spec:
  predeclared: true
  broker: "rmq-knative:5672/"
  user:
    secretKeyRef:
      name: rmq-knative-default-user
      key: username
  password:
    secretKeyRef:
      name: rmq-knative-default-user
      key: password
  connectionSecret:
    name: rmq-knative-default-user
  channelConfig:
    globalQos: false
  exchangeConfig:
    name: "hungryman-search-criteria"
    type: "topic"
    durable: true
  queueConfig:
    name: "hungryman-search-criteria"
    routingKey: "#"
    durable: true
  sink:
    uri: http://hungryman-sequence-kn-sequence-0-kn-channel.workloads.svc.cluster.local