---
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: hungryman-sequence
  namespace: workload_namespace
spec:
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: hungryman-search-proc
      uri: /processSearch
    - ref:
      uri: http://hungryman-available-parallel-kn-parallel-kn-channel.workload_namespace.svc.cluster.local
---
apiVersion: flows.knative.dev/v1
kind: Parallel
metadata:
  name: hungryman-available-parallel
  namespace: workload_namespace
spec:
  branches:
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: hungryman-availability
        uri: /processAvailability
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: hungryman-notify
        uri: /notifyAvailability

---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  labels:
    eventing.knative.dev/SourceName: hungryman-search-criteria-rabbit-source
  name: hungryman-search-criteria-exchnage
  namespace: workload_namespace
spec:
  durable: true
  name: hungryman-search-criteria
  rabbitmqClusterReference:
    name: rmq_instance_name
    namespace: rmq_service_namespace
  type: topic
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  labels:
    eventing.knative.dev/SourceName: hungryman-search-criteria-rabbit-source
  name: hungryman-search-criteria-queue
  namespace: workload_namespace
spec:
  durable: true
  autoDelete: false
  name: hungryman-search-criteria
  rabbitmqClusterReference:
    name: rmq_instance_name
    namespace: rmq_service_namespace
  type: quorum
  vhost: /
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  labels:
    eventing.knative.dev/SourceName: hungryman-search-criteria-rabbit-source
  name: hungryman-search-criteria-binding
  namespace: workload_namespace
spec:
  source: hungryman-search-criteria
  destination: hungryman-search-criteria
  destinationType: queue
  routingKey: "#"
  rabbitmqClusterReference:
    name: rmq_instance_name
    namespace: rmq_service_namespace
  vhost: /
---
apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: hungryman-search-criteria-rabbit-source
  namespace: workload_namespace
spec:

  rabbitmqClusterReference:
    name: rmq_instance_name
    namespace: rmq_service_namespace
  rabbitmqResourcesConfig:
    predeclared: true 
    parallelism: 5
    queueName: hungryman-search-criteria
  sink:
    uri: http://hungryman-sequence-kn-sequence-0-kn-channel.workload_namespace.svc.cluster.local